version: 0.0
os: linux
files:
   - source: /
     destination: /home/ec2-user/desarrollo/com.basic.example/
permissions:
   - object: /home/ec2-user/desarrollo/com.basic.example
     pattern: "**"
     owner: apache
     group: apache
     mode: 777
     type:
       - file
hooks:
   AfterInstall:
    - location: scripts/desplegar.sh